version: "3.9"

services:
  web:
    build: .
    command: gunicorn kaya.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=kaya.settings
    networks:
      - backend
    env_file:
      - .env

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: nex
      POSTGRES_USER: nex
      POSTGRES_PASSWORD: studio
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - 6392:6379
    networks:
      - backend

  celery:
    build: .
    command: celery -A kaya worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  es_data:
